### ISSUE TITLE
Allow navigation in embark from consult-gh searches similar to consult-grep

### ISSUE THREAD

**Issue by ParetoOptimalDev** [armindarvish/consult-gh#76] opened 2023-10-20 21:19 UTC
**Is your feature request related to a problem? Please describe.**

Yes, being able to sift quickly through github code search results.

The embark functionality introduced in #69 and #70 works great and improves this a lot.

**Describe the solution you'd like**

Navigating search results with n/p in embark buffer generated from `consult-gh-code-search` using complilation mode like consult-grep.

When I made my original request, I had assumed the functionality that happens with `consult-grep` of being able to hit `n` to go to the next result and having it open in a buffer beside is really smooth.

here is a gif to demonstrate:

![output-2023-10-20-16:17:18](https://github.com/armindarvish/consult-gh/assets/93023868/f511c8e7-03b5-42f9-804f-6e11a7f90899)

**Describe alternatives you've considered**

Just using the buffer as is, but more manually calling =n= and =RET= myself more.

**Additional context**

**Comment by armindarvish** [comment] 2023-10-21 10:32
@ParetoOptimalDev I am not sure if this is a good idea as a general solution, so my suggestion would be to make some script to achieve it in your setup (see below), rather than making this default for everyone.

The reason this might noe be a great idea is that when you open the result of each search code, consult-gh is making some api calls to download the file containing the code (the entire file not just the code snippet) and puts in a unique subdirectory of `consult-gh-tempdir`. If you open the same result twice, it will download the file twice and opens them in two different buffers (because two different unique path). This is to ensure we always show the latest version of the original file pulled from the source rather than some local copy. Going over code search results and opening them would mean you are downloading many files and it can be slow if the files are big. In general it is probably better if the user actively choses to download/open the file by hitting "RET". This is just one more key press after all and not a major inconvenience.

That said here is a quick hack to rebind `n` and `p` to achieve what you are asking for:

```emacs-lisp
(defun my:push-next-button ()
(interactive)
(forward-button 1)
(push-button)
)

(defun my:push-previous-button ()
(interactive)
(backward-button 1)
(push-button)
)

(define-key embark-collect-mode-map "n" #'my:push-next-button)
(define-key embark-collect-mode-map "p" #'my:push-previous-button)
```

Note that in this case you are rebinding `n` and `p` in `embark-collect-mode-map` so this will affect all embark collect buffers.

Alternatively you have to override the embark collect for `consult-gh-search-code`, similar to how it is done for `consult-grep` in [embark-consult.el](https://github.com/oantolin/embark/blob/master/embark-consult.el). Look at `embark-consult-export-grep`.

**Comment by ParetoOptimalDev** [comment] 2023-10-22 04:14
Firstly, thanks for the assistance!

Secondly, perhaps I can make a convincing argument this should be the default or a configuration option.

> If you open the same result twice, it will download the file twice and opens them in two different buffers (because two different unique path).

> This is to ensure we always show the latest version of the original file pulled from the source rather than some local copy.

What if each result set, whether in consult or in an embark exported buffer, had a cache.

This would mean that you wouldn't get the new results until you did a new search.

Perhaps even hitting `g` to refresh clears the cache.

Then this workflow like consult-grep has is possible without having too many api calls.

My use-cases for code searching don't frequently include "always have most updated version of the file" though, so this might be annoying for you or other users.

**Comment by ParetoOptimalDev** [comment] 2023-10-22 04:24
What I'd really like is if github offered context for their searches from the API and I've created a discussion about it here previously:

https://github.com/orgs/community/discussions/69789

After trying out the code above, I can definitely see why you say maybe not everyone would want it.

Perhaps having consult-preview work when a certain key is pressed would be an ideal middle ground?

So the workflow would be search, move to something that seems promising, hit consult-preview key to load it, then hitting enter switches to that already loaded buffer.

**Comment by armindarvish** [comment] 2023-11-13 00:20
@ParetoOptimalDev I understand your argument,

I agrre with the suggestion that using previe key and then selecting it should not download the file twice. This was the intended behavior, but I just tried `consult-gh-search-code` and I realize that it is not the case. If I first open the preview and then select the candidate, I get two different buffers (and two different files downloaded separately). I need to fix this! Let me go over the code again and figure out if there is a good way to avoid that.

More generally, using a cache (beyond within the same instance of an interactive command) can be tricky (especially with `code search`) because then we have to track when each single file was downloaded and in code search the same file may be accessed multiple times depending on what the user searches for. Tracking which file has been visited and when becomes a mess and it would be risky because the local copies may deviate from the source file. That said, `gh` itself does provide some caching that can probably be used for this purpose, but I am going to need to spend some time playing with that before I can find the right middle ground!

**Comment by armindarvish** [comment] 2024-08-05 20:38
I just pushed some commits to develop, where we reuse the temporary directory/files with a customizable cache time. This allows reusing the downloaded file for a preview when selecting a file. I think this is a good middle ground between cloning entire repositories and pulling and downloading multiple copies of the same files every single time the user wants to view the file.

I am closing this issue now, but feel free to reopen if some new issues come up!

**Closed by armindarvish** 2024-08-05 20:38 UTC
