### ISSUE TITLE
helm conflicts with consult-gh

### ISSUE THREAD

**Issue by fkgruber** [armindarvish/consult-gh#136] opened 2024-08-29 00:09 UTC
**Describe the bug**
activating helm breaks consult-gh

**To Reproduce**
After installing helm if you activate helm:
```
(helm-mod 1)
consult-gh-issue-list 
openvax/isovar
```
give error:

```
helm-M-x-execute-command: Wrong type argument: stringp, nil
```

debug:
```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  substring-no-properties(nil)
  consult-gh--issue-browse-url-action(("nil:nil"))
  consult-gh-issue-list()
  funcall-interactively(consult-gh-issue-list)
  call-interactively(consult-gh-issue-list record nil)
  command-execute(consult-gh-issue-list record)
  helm-M-x-execute-command(consult-gh-issue-list)
  helm-execute-selection-action-1()
  helm-execute-selection-action()
  helm-internal((((name . "Emacs Commands history") (init #f(compiled-function () #<bytecode 0x1b2a28d91fce0087>)) (candidates . helm-candidates-in-buffer) (cleanup . helm-M-x--unwind-forms) (keymap keymap (keymap ...) keymap (29 . helm-M-x-toggle-short-doc) (21 . helm-M-x-universal-argument) keymap (27 keymap ...) (C-return . helm-cr-empty-string) keymap (tab . helm-execute-persistent-action) (f12 . #f(compiled-function () ... #<bytecode 0x1980ef08a22e80>)) (f11 . #f(compiled-function () ... #<bytecode 0x1980ef08a41e80>)) (f10 . #f(compiled-function () ... #<bytecode 0x1980ef08a50e80>)) (f9 . #f(compiled-function () ... #<bytecode 0x1980ef08617e80>)) (f8 . #f(compiled-function () ... #<bytecode 0x1980ef08606e80>)) (f7 . #f(compiled-function () ... #<bytecode 0x1980ef08a05e80>)) (f6 . #f(compiled-function () ... #<bytecode 0x1980ef08a14e80>)) (f5 . #f(compiled-function () ... #<bytecode 0x1980ef0867be80>)) (f4 . #f(compiled-function () ... #<bytecode 0x1980ef0866ae80>)) (f3 . #f(compiled-function () ... #<bytecode 0x1980ef086a9e80>)) (f2 . #f(compiled-function () ... #<bytecode 0x1980ef086b8e80>)) (menu-bar keymap ...) (help keymap ...) (23 . helm-helm-yank-text-at-point-with-subkeys) (f1 . #f(compiled-function () ... #<bytecode 0x1980ef0863fe80>)) (8 keymap ... ... ... ... ... ...) (20 . helm-toggle-resplit-and-swap-windows) (C-tab . undefined) (67108897 . helm-toggle-suspend-update) (26 . helm-toggle-full-frame) (3 keymap ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ...) ...) (action . helm-type-command-actions) (persistent-action . helm-M-x-persistent-action) (persistent-help . "Describe this command") (help-message . helm-M-x-help-message) (requires-pattern . 0) (filtered-candidate-transformer helm-M-x-transformer #f(compiled-function (candidates source) #<bytecode 0x1965dc69e2590cfb>) helm-fuzzy-highlight-matches) (volatile . t) (match identity) (fuzzy-match . t) (redisplay . identity) (nomark . t) (coerce . helm-symbolify) (header-line . #("TAB: Describe this command (keep..." 0 3 ...)) (resume . helm-M-x-resume-fn) (multimatch . t) (must-match . t) (group . helm-command) (data . #f(compiled-function () #<bytecode -0xcff461661c93230>)) (get-line . buffer-substring-no-properties) (search helm-mm-exact-search helm-mm-search helm-candidates-in-buffer-search-default-fn helm-fuzzy-search)) ((name . "Emacs Commands") (init #f(compiled-function () #<bytecode -0x1d11866c94c786dd>)) (candidates . helm-candidates-in-buffer) (cleanup . helm-M-x--unwind-forms) (keymap keymap (keymap ...) keymap (29 . helm-M-x-toggle-short-doc) (21 . helm-M-x-universal-argument) keymap (27 keymap ...) (C-return . helm-cr-empty-string) keymap (tab . helm-execute-persistent-action) (f12 . #f(compiled-function () ... #<bytecode 0x1980ef08a22e80>)) (f11 . #f(compiled-function () ... #<bytecode 0x1980ef08a41e80>)) (f10 . #f(compiled-function () ... #<bytecode 0x1980ef08a50e80>)) (f9 . #f(compiled-function () ... #<bytecode 0x1980ef08617e80>)) (f8 . #f(compiled-function () ... #<bytecode 0x1980ef08606e80>)) (f7 . #f(compiled-function () ... #<bytecode 0x1980ef08a05e80>)) (f6 . #f(compiled-function () ... #<bytecode 0x1980ef08a14e80>)) (f5 . #f(compiled-function () ... #<bytecode 0x1980ef0867be80>)) (f4 . #f(compiled-function () ... #<bytecode 0x1980ef0866ae80>)) (f3 . #f(compiled-function () ... #<bytecode 0x1980ef086a9e80>)) (f2 . #f(compiled-function () ... #<bytecode 0x1980ef086b8e80>)) (menu-bar keymap ...) (help keymap ...) (23 . helm-helm-yank-text-at-point-with-subkeys) (f1 . #f(compiled-function () ... #<bytecode 0x1980ef0863fe80>)) (8 keymap ... ... ... ... ... ...) (20 . helm-toggle-resplit-and-swap-windows) (C-tab . undefined) (67108897 . helm-toggle-suspend-update) (26 . helm-toggle-full-frame) (3 keymap ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ...) ...) (action . helm-type-command-actions) (persistent-action . helm-M-x-persistent-action) (persistent-help . "Describe this command") (help-message . helm-M-x-help-message) (requires-pattern . 0) (filtered-candidate-transformer helm-M-x-transformer #f(compiled-function (candidates source) #<bytecode 0x1965dc69e2590cfb>) helm-fuzzy-highlight-matches) (volatile . t) (match identity) (fuzzy-match . t) (redisplay . identity) (nomark . t) (coerce . helm-symbolify) (header-line . #("TAB: Describe this command (keep..." 0 3 ...)) (resume . helm-M-x-resume-fn) (multimatch . t) (must-match . t) (group . helm-command) (data . #f(compiled-function () #<bytecode 0xb64cf1a7161d2a6>)) (get-line . buffer-substring-no-properties) (search helm-mm-exact-search helm-mm-search helm-candidates-in-buffer-search-default-fn helm-fuzzy-search))) nil "M-x " nil nil "*helm M-x*" nil nil helm-M-x-input-history)
  apply(helm-internal ((((name . "Emacs Commands history") (init #f(compiled-function () #<bytecode 0x1b2a28d91fce0087>)) (candidates . helm-candidates-in-buffer) (cleanup . helm-M-x--unwind-forms) (keymap keymap ... keymap ... ... keymap ... ... keymap ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ...) (action . helm-type-command-actions) (persistent-action . helm-M-x-persistent-action) (persistent-help . "Describe this command") (help-message . helm-M-x-help-message) (requires-pattern . 0) (filtered-candidate-transformer helm-M-x-transformer #f(compiled-function (candidates source) #<bytecode 0x1965dc69e2590cfb>) helm-fuzzy-highlight-matches) (volatile . t) (match identity) (fuzzy-match . t) (redisplay . identity) (nomark . t) (coerce . helm-symbolify) (header-line . ...) (resume . helm-M-x-resume-fn) (multimatch . t) (must-match . t) (group . helm-command) (data . #f(compiled-function () #<bytecode -0xcff461661c93230>)) (get-line . buffer-substring-no-properties) (search helm-mm-exact-search helm-mm-search helm-candidates-in-buffer-search-default-fn helm-fuzzy-search)) ((name . "Emacs Commands") (init #f(compiled-function () #<bytecode -0x1d11866c94c786dd>)) (candidates . helm-candidates-in-buffer) (cleanup . helm-M-x--unwind-forms) (keymap keymap ... keymap ... ... keymap ... ... keymap ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ...) (action . helm-type-command-actions) (persistent-action . helm-M-x-persistent-action) (persistent-help . "Describe this command") (help-message . helm-M-x-help-message) (requires-pattern . 0) (filtered-candidate-transformer helm-M-x-transformer #f(compiled-function (candidates source) #<bytecode 0x1965dc69e2590cfb>) helm-fuzzy-highlight-matches) (volatile . t) (match identity) (fuzzy-match . t) (redisplay . identity) (nomark . t) (coerce . helm-symbolify) (header-line . ...) (resume . helm-M-x-resume-fn) (multimatch . t) (must-match . t) (group . helm-command) (data . #f(compiled-function () #<bytecode 0xb64cf1a7161d2a6>)) (get-line . buffer-substring-no-properties) (search helm-mm-exact-search helm-mm-search helm-candidates-in-buffer-search-default-fn helm-fuzzy-search))) nil "M-x " nil nil "*helm M-x*" nil nil helm-M-x-input-history))
  helm((((name . "Emacs Commands history") (init #f(compiled-function () #<bytecode 0x1b2a28d91fce0087>)) (candidates . helm-candidates-in-buffer) (cleanup . helm-M-x--unwind-forms) (keymap keymap (keymap ...) keymap (29 . helm-M-x-toggle-short-doc) (21 . helm-M-x-universal-argument) keymap (27 keymap ...) (C-return . helm-cr-empty-string) keymap (tab . helm-execute-persistent-action) (f12 . #f(compiled-function () ... #<bytecode 0x1980ef08a22e80>)) (f11 . #f(compiled-function () ... #<bytecode 0x1980ef08a41e80>)) (f10 . #f(compiled-function () ... #<bytecode 0x1980ef08a50e80>)) (f9 . #f(compiled-function () ... #<bytecode 0x1980ef08617e80>)) (f8 . #f(compiled-function () ... #<bytecode 0x1980ef08606e80>)) (f7 . #f(compiled-function () ... #<bytecode 0x1980ef08a05e80>)) (f6 . #f(compiled-function () ... #<bytecode 0x1980ef08a14e80>)) (f5 . #f(compiled-function () ... #<bytecode 0x1980ef0867be80>)) (f4 . #f(compiled-function () ... #<bytecode 0x1980ef0866ae80>)) (f3 . #f(compiled-function () ... #<bytecode 0x1980ef086a9e80>)) (f2 . #f(compiled-function () ... #<bytecode 0x1980ef086b8e80>)) (menu-bar keymap ...) (help keymap ...) (23 . helm-helm-yank-text-at-point-with-subkeys) (f1 . #f(compiled-function () ... #<bytecode 0x1980ef0863fe80>)) (8 keymap ... ... ... ... ... ...) (20 . helm-toggle-resplit-and-swap-windows) (C-tab . undefined) (67108897 . helm-toggle-suspend-update) (26 . helm-toggle-full-frame) (3 keymap ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ...) ...) (action . helm-type-command-actions) (persistent-action . helm-M-x-persistent-action) (persistent-help . "Describe this command") (help-message . helm-M-x-help-message) (requires-pattern . 0) (filtered-candidate-transformer helm-M-x-transformer #f(compiled-function (candidates source) #<bytecode 0x1965dc69e2590cfb>) helm-fuzzy-highlight-matches) (volatile . t) (match identity) (fuzzy-match . t) (redisplay . identity) (nomark . t) (coerce . helm-symbolify) (header-line . #("TAB: Describe this command (keep..." 0 3 ...)) (resume . helm-M-x-resume-fn) (multimatch . t) (must-match . t) (group . helm-command) (data . #f(compiled-function () #<bytecode -0xcff461661c93230>)) (get-line . buffer-substring-no-properties) (search helm-mm-exact-search helm-mm-search helm-candidates-in-buffer-search-default-fn helm-fuzzy-search)) ((name . "Emacs Commands") (init #f(compiled-function () #<bytecode -0x1d11866c94c786dd>)) (candidates . helm-candidates-in-buffer) (cleanup . helm-M-x--unwind-forms) (keymap keymap (keymap ...) keymap (29 . helm-M-x-toggle-short-doc) (21 . helm-M-x-universal-argument) keymap (27 keymap ...) (C-return . helm-cr-empty-string) keymap (tab . helm-execute-persistent-action) (f12 . #f(compiled-function () ... #<bytecode 0x1980ef08a22e80>)) (f11 . #f(compiled-function () ... #<bytecode 0x1980ef08a41e80>)) (f10 . #f(compiled-function () ... #<bytecode 0x1980ef08a50e80>)) (f9 . #f(compiled-function () ... #<bytecode 0x1980ef08617e80>)) (f8 . #f(compiled-function () ... #<bytecode 0x1980ef08606e80>)) (f7 . #f(compiled-function () ... #<bytecode 0x1980ef08a05e80>)) (f6 . #f(compiled-function () ... #<bytecode 0x1980ef08a14e80>)) (f5 . #f(compiled-function () ... #<bytecode 0x1980ef0867be80>)) (f4 . #f(compiled-function () ... #<bytecode 0x1980ef0866ae80>)) (f3 . #f(compiled-function () ... #<bytecode 0x1980ef086a9e80>)) (f2 . #f(compiled-function () ... #<bytecode 0x1980ef086b8e80>)) (menu-bar keymap ...) (help keymap ...) (23 . helm-helm-yank-text-at-point-with-subkeys) (f1 . #f(compiled-function () ... #<bytecode 0x1980ef0863fe80>)) (8 keymap ... ... ... ... ... ...) (20 . helm-toggle-resplit-and-swap-windows) (C-tab . undefined) (67108897 . helm-toggle-suspend-update) (26 . helm-toggle-full-frame) (3 keymap ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ...) ...) (action . helm-type-command-actions) (persistent-action . helm-M-x-persistent-action) (persistent-help . "Describe this command") (help-message . helm-M-x-help-message) (requires-pattern . 0) (filtered-candidate-transformer helm-M-x-transformer #f(compiled-function (candidates source) #<bytecode 0x1965dc69e2590cfb>) helm-fuzzy-highlight-matches) (volatile . t) (match identity) (fuzzy-match . t) (redisplay . identity) (nomark . t) (coerce . helm-symbolify) (header-line . #("TAB: Describe this command (keep..." 0 3 ...)) (resume . helm-M-x-resume-fn) (multimatch . t) (must-match . t) (group . helm-command) (data . #f(compiled-function () #<bytecode 0xb64cf1a7161d2a6>)) (get-line . buffer-substring-no-properties) (search helm-mm-exact-search helm-mm-search helm-candidates-in-buffer-search-default-fn helm-fuzzy-search))) nil "M-x " nil nil "*helm M-x*" nil nil helm-M-x-input-history)
  apply(helm ((((name . "Emacs Commands history") (init #f(compiled-function () #<bytecode 0x1b2a28d91fce0087>)) (candidates . helm-candidates-in-buffer) (cleanup . helm-M-x--unwind-forms) (keymap keymap ... keymap ... ... keymap ... ... keymap ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ...) (action . helm-type-command-actions) (persistent-action . helm-M-x-persistent-action) (persistent-help . "Describe this command") (help-message . helm-M-x-help-message) (requires-pattern . 0) (filtered-candidate-transformer helm-M-x-transformer #f(compiled-function (candidates source) #<bytecode 0x1965dc69e2590cfb>) helm-fuzzy-highlight-matches) (volatile . t) (match identity) (fuzzy-match . t) (redisplay . identity) (nomark . t) (coerce . helm-symbolify) (header-line . ...) (resume . helm-M-x-resume-fn) (multimatch . t) (must-match . t) (group . helm-command) (data . #f(compiled-function () #<bytecode -0xcff461661c93230>)) (get-line . buffer-substring-no-properties) (search helm-mm-exact-search helm-mm-search helm-candidates-in-buffer-search-default-fn helm-fuzzy-search)) ((name . "Emacs Commands") (init #f(compiled-function () #<bytecode -0x1d11866c94c786dd>)) (candidates . helm-candidates-in-buffer) (cleanup . helm-M-x--unwind-forms) (keymap keymap ... keymap ... ... keymap ... ... keymap ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ...) (action . helm-type-command-actions) (persistent-action . helm-M-x-persistent-action) (persistent-help . "Describe this command") (help-message . helm-M-x-help-message) (requires-pattern . 0) (filtered-candidate-transformer helm-M-x-transformer #f(compiled-function (candidates source) #<bytecode 0x1965dc69e2590cfb>) helm-fuzzy-highlight-matches) (volatile . t) (match identity) (fuzzy-match . t) (redisplay . identity) (nomark . t) (coerce . helm-symbolify) (header-line . ...) (resume . helm-M-x-resume-fn) (multimatch . t) (must-match . t) (group . helm-command) (data . #f(compiled-function () #<bytecode 0xb64cf1a7161d2a6>)) (get-line . buffer-substring-no-properties) (search helm-mm-exact-search helm-mm-search helm-candidates-in-buffer-search-default-fn helm-fuzzy-search))) nil "M-x " nil nil "*helm M-x*" nil nil helm-M-x-input-history))
  helm(:sources (((name . "Emacs Commands history") (init #f(compiled-function () #<bytecode 0x1b2a28d91fce0087>)) (candidates . helm-candidates-in-buffer) (cleanup . helm-M-x--unwind-forms) (keymap keymap (keymap ...) keymap (29 . helm-M-x-toggle-short-doc) (21 . helm-M-x-universal-argument) keymap (27 keymap ...) (C-return . helm-cr-empty-string) keymap (tab . helm-execute-persistent-action) (f12 . #f(compiled-function () ... #<bytecode 0x1980ef08a22e80>)) (f11 . #f(compiled-function () ... #<bytecode 0x1980ef08a41e80>)) (f10 . #f(compiled-function () ... #<bytecode 0x1980ef08a50e80>)) (f9 . #f(compiled-function () ... #<bytecode 0x1980ef08617e80>)) (f8 . #f(compiled-function () ... #<bytecode 0x1980ef08606e80>)) (f7 . #f(compiled-function () ... #<bytecode 0x1980ef08a05e80>)) (f6 . #f(compiled-function () ... #<bytecode 0x1980ef08a14e80>)) (f5 . #f(compiled-function () ... #<bytecode 0x1980ef0867be80>)) (f4 . #f(compiled-function () ... #<bytecode 0x1980ef0866ae80>)) (f3 . #f(compiled-function () ... #<bytecode 0x1980ef086a9e80>)) (f2 . #f(compiled-function () ... #<bytecode 0x1980ef086b8e80>)) (menu-bar keymap ...) (help keymap ...) (23 . helm-helm-yank-text-at-point-with-subkeys) (f1 . #f(compiled-function () ... #<bytecode 0x1980ef0863fe80>)) (8 keymap ... ... ... ... ... ...) (20 . helm-toggle-resplit-and-swap-windows) (C-tab . undefined) (67108897 . helm-toggle-suspend-update) (26 . helm-toggle-full-frame) (3 keymap ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ...) ...) (action . helm-type-command-actions) (persistent-action . helm-M-x-persistent-action) (persistent-help . "Describe this command") (help-message . helm-M-x-help-message) (requires-pattern . 0) (filtered-candidate-transformer helm-M-x-transformer #f(compiled-function (candidates source) #<bytecode 0x1965dc69e2590cfb>) helm-fuzzy-highlight-matches) (volatile . t) (match identity) (fuzzy-match . t) (redisplay . identity) (nomark . t) (coerce . helm-symbolify) (header-line . #("TAB: Describe this command (keep..." 0 3 ...)) (resume . helm-M-x-resume-fn) (multimatch . t) (must-match . t) (group . helm-command) (data . #f(compiled-function () #<bytecode -0xcff461661c93230>)) (get-line . buffer-substring-no-properties) (search helm-mm-exact-search helm-mm-search helm-candidates-in-buffer-search-default-fn helm-fuzzy-search)) ((name . "Emacs Commands") (init #f(compiled-function () #<bytecode -0x1d11866c94c786dd>)) (candidates . helm-candidates-in-buffer) (cleanup . helm-M-x--unwind-forms) (keymap keymap (keymap ...) keymap (29 . helm-M-x-toggle-short-doc) (21 . helm-M-x-universal-argument) keymap (27 keymap ...) (C-return . helm-cr-empty-string) keymap (tab . helm-execute-persistent-action) (f12 . #f(compiled-function () ... #<bytecode 0x1980ef08a22e80>)) (f11 . #f(compiled-function () ... #<bytecode 0x1980ef08a41e80>)) (f10 . #f(compiled-function () ... #<bytecode 0x1980ef08a50e80>)) (f9 . #f(compiled-function () ... #<bytecode 0x1980ef08617e80>)) (f8 . #f(compiled-function () ... #<bytecode 0x1980ef08606e80>)) (f7 . #f(compiled-function () ... #<bytecode 0x1980ef08a05e80>)) (f6 . #f(compiled-function () ... #<bytecode 0x1980ef08a14e80>)) (f5 . #f(compiled-function () ... #<bytecode 0x1980ef0867be80>)) (f4 . #f(compiled-function () ... #<bytecode 0x1980ef0866ae80>)) (f3 . #f(compiled-function () ... #<bytecode 0x1980ef086a9e80>)) (f2 . #f(compiled-function () ... #<bytecode 0x1980ef086b8e80>)) (menu-bar keymap ...) (help keymap ...) (23 . helm-helm-yank-text-at-point-with-subkeys) (f1 . #f(compiled-function () ... #<bytecode 0x1980ef0863fe80>)) (8 keymap ... ... ... ... ... ...) (20 . helm-toggle-resplit-and-swap-windows) (C-tab . undefined) (67108897 . helm-toggle-suspend-update) (26 . helm-toggle-full-frame) (3 keymap ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ...) ...) (action . helm-type-command-actions) (persistent-action . helm-M-x-persistent-action) (persistent-help . "Describe this command") (help-message . helm-M-x-help-message) (requires-pattern . 0) (filtered-candidate-transformer helm-M-x-transformer #f(compiled-function (candidates source) #<bytecode 0x1965dc69e2590cfb>) helm-fuzzy-highlight-matches) (volatile . t) (match identity) (fuzzy-match . t) (redisplay . identity) (nomark . t) (coerce . helm-symbolify) (header-line . #("TAB: Describe this command (keep..." 0 3 ...)) (resume . helm-M-x-resume-fn) (multimatch . t) (must-match . t) (group . helm-command) (data . #f(compiled-function () #<bytecode 0xb64cf1a7161d2a6>)) (get-line . buffer-substring-no-properties) (search helm-mm-exact-search helm-mm-search helm-candidates-in-buffer-search-default-fn helm-fuzzy-search))) :prompt "M-x " :buffer "*helm M-x*" :history helm-M-x-input-history :truncate-lines t)
  helm-M-x-read-extended-command([python-imenu-format-parent-item-label magit-section-show-headings AND calendar-forward-week helm-select-action tramp-completion-handle-file-name-all-completions 0 straight-vc-clone python-nav-beginning-of-defun-regexp Reduce\ To:\ to\ Cc: ob-session-async-R-indicator magit-revision-filter-files-on-follow treepy-vector-zip yas-x-prompt cc-vars &error rng-parse-validate-file magit-xref-insert-button helm-ff-query-replace-fnames-history-to text2 tramp-compat-string-equal-ignore-case edebug-mode-on-hook message-expand-name-databases transient:magit-diff-refresh:--irreversible-delete 0 consult--focus-lines-overlays minibuffer-text-before-history magit-list-modified-modules ns-l-compact-sequence which-key--stop-timer EXPLAIN vc-annotate :mac overlap-beg buf-list rng-match-infer-start-tag-namespace 0 org-agenda-regexp-filter-preset python-skeleton-available kmacro-p hs-toggle-hiding magit-filename dired-do-chmod server--on-display-p star_count check-declare xref-group transient:magit-log:--dense Hardlink... eieio-instance-tracker-child-p ...])
  helm-M-x(nil)
  funcall-interactively(helm-M-x nil)
  call-interactively(helm-M-x nil nil)
  command-execute(helm-M-x)

```

If I disable helm 
```
(helm-mode 0)
```
then it works

**Important Information:**
 ```
OS: mac os
Version of Emacs : 29.1
Version of gh (run gh --version in a shell)
gh version 2.52.0 (2024-06-24)
https://github.com/cli/cli/releases/tag/v2.52.0
Version of consult 20240824.800
The installation method and the configuration you are using with your consult-gh.
(use-package consult-gh
 :straight (consult-gh :type git :host github :repo "armindarvish/consult-gh")
 :after consult

 :config
 ;;add your main GitHub account (replace "armindarvish" with your user or org)
 (add-to-list 'consult-gh-default-orgs-list "armindarvish")

 ;;use "gh org list" to get a list of all your organizations and adds them to default list
 (setq consult-gh-default-orgs-list (append consult-gh-default-orgs-list (remove "" (split-string (or (consult-gh--command-to-string "org" "list") "") "\n"))))

 ;; set the default folder for cloning repositories, By default Consult-GH will confirm this before cloning
 (setq consult-gh-default-clone-directory "~/gitRepos/"))
```

**Comment by armindarvish** [comment] 2024-08-29 00:37
@fkgruber Try running `consult-grep` with helm-mode on. If that does not work either, then the issue is the compatibility of consult and helm, which we cannot do anything about in `consult-gh`.

I cannot find anything on compatibility between helm and consult. You have to ask @minad in the upstream consult about that, but I'd imagine that helm is not supported in which case you have to use another completion framework like Vertico, or a similar package.

Closing this now, since there is nothing to do in `consult-gh`.

**Closed** 2024-08-29 00:38 UTC
