### ISSUE TITLE
Opening an issue with `forge` fails

### ISSUE THREAD

**Issue by benthamite** [armindarvish/consult-gh#102] opened 2024-01-17 12:43 UTC
**Describe the bug**
When `consult-gh-issue-action` is set to `consult-gh-forge--issue-view-action`, `consult-gh` fails to open the selected issue.

**To Reproduce**
1. `M-x consult-gh-search-issues`
2. Enter a search string, e.g. "consult-gh"
3. Select a search result, e.g. issue #101

**Expected behavior**
The issue is opened in a `forge` buffer.

**Important Information:**
 - macOS Sonoma 14.2.1
 - GNU Emacs 30.0.50 (build 1, aarch64-apple-darwin22.5.0, NS appkit-2299.60 Version 13.4.1 (c) (Build 22F770820d)) of 2023-08-27
 - gh version 2.40.1 (2023-12-13)
https://github.com/cli/cli/releases/tag/v2.40.1
 - consult version 1.1

config:

``` emacs-lisp
(use-package consult-gh
  :elpaca (consult-gh
           :host github
           :repo "armindarvish/consult-gh")
  :after consult forge
  :demand t
  :config
  (require 'consult-gh-embark)
  (require 'consult-gh-forge)
  (setq consult-gh-default-clone-directory "~/source/")
  (setq consult-gh-repo-maxnum 30)
  (setq consult-gh-issues-maxnum 100)
  (setq consult-gh-show-preview nil)
  (setq consult-gh-preview-key 'any)
  (setq consult-gh-preview-buffer-mode 'org-mode)
  (setq consult-gh-repo-action #'consult-gh--repo-browse-files-action)
  (setq consult-gh-issue-action #'consult-gh-forge--issue-view-action)
  (setq consult-gh-pr-action #'consult-gh-forge--pr-view-action)
  (setq consult-gh-code-action #'consult-gh--code-view-action)
  (setq consult-gh-file-action #'consult-gh--files-view-action)
  (setq consult-gh-issues-state-to-show "all")

  (dolist (var '(consult-gh--known-orgs-list
                 consult-gh--known-repos-list))
    (push var savehist-additional-variables)))
```

backtrace:

``` emacs-lisp
Debugger entered--Lisp error: (void-variable sparse-p)
  consult-gh-forge--add-repository("https://github.com/armindarvish/consult-gh")
  consult-gh-forge--add-topic("https://github.com/armindarvish/consult-gh" 97)
  consult-gh-forge--issue-view("armindarvish/consult-gh" "97")
  consult-gh-forge--issue-view-action(("97:Warning (comp): consult-gh-embark.el: Error: Symbol's value as variable is void consult-preview-key" :repo "armindarvish/consult-gh" :user "armindarvish" :issue "97" :state "CLOSED" :title "Warning (comp): consult-gh-embark.el: Error: Symbol's value as variable is void consult-preview-key" :tags "" :date "2023-11-16" :query "consult-gh--issue-view-action"))
  consult-gh-search-issues()
  funcall-interactively(consult-gh-search-issues)
  command-execute(consult-gh-search-issues record)
  execute-extended-command(nil "consult-gh-search-issues" nil)
  funcall-interactively(execute-extended-command nil "consult-gh-search-issues" nil)
  command-execute(execute-extended-command)
```

**Comment by armindarvish** [comment] 2024-02-06 09:51
@benthamite I cannot reproduce this issue (see the screenshot below). From the error you posted, it looks like `consult-preview-key` is not defined, which likely means `consult` is not properly loaded before `consult-gh`. If I have to guess, this is either caused by 
1- how elpaca pulls packages. You need to make sure consult is properly loaded before loading consult-gh

or

2- there is some compiling issue.

I'd suggest try installing without elpaca in a clean environment (e.g. emacs -Q) and see if you still have the same problem. 

![Screen Recording 2024-02-06 at 1 39 33 AM](https://github.com/armindarvish/consult-gh/assets/18317557/75fcd57f-3df8-48c1-8036-3d49c0437f69)

**Comment by benthamite** [comment] 2024-02-22 12:45
Thanks, @armindarvish. I tried to further debug this, but now I’m getting a slightly different error:

``` emacs-lisp
Debugger entered--Lisp error: (void-function forge--zap-repository-cache)
  forge--zap-repository-cache(#<forge-github-repository forge-github-repository-59e777a4>)
  consult-gh-forge--pull-topic("https://github.com/armindarvish/consult-gh" 101)
  consult-gh-forge--add-topic("https://github.com/armindarvish/consult-gh" 101)
  consult-gh-forge--issue-view("armindarvish/consult-gh" "101")
  consult-gh-forge--issue-view-action(("101:`consult-gh-repo-fork` does not add a remote for the fork" :repo "armindarvish/consult-gh" :user "armindarvish" :issue "101" :state "CLOSED" :title "`consult-gh-repo-fork` does not add a remote for the fork" :tags "" :date "2024-02-09" :query " does not add a remote for the fork "))
  consult-gh-search-issues()
  funcall-interactively(consult-gh-search-issues)
  command-execute(consult-gh-search-issues record)
  execute-extended-command(nil #("consult-gh-search-issues" 0 24 (fontified nil)) nil)
  funcall-interactively(execute-extended-command nil #("consult-gh-search-issues" 0 24 (fontified nil)) nil)
  command-execute(execute-extended-command)
```

It appears that the function `forge--zap-repository-cache` was removed a week ago (commit `3908514`).

**Comment by armindarvish** [comment] 2024-02-27 18:39
@benthamite Ok, that'll take a bit longer for me to look into because I have to update everything to make it compatible with the latest updates in Forge. In the meanwhile, you can use an older version of forge until I find some time to go over the code and figure out how to hack forge commands again 😃.

**Comment by armindarvish** [comment] 2024-08-02 07:44
Just fixed the issue in develop branch. Closing this now.

**Closed by armindarvish** 2024-08-02 07:44 UTC
