### ISSUE TITLE
`consult-gh-repo-fork` does not add a remote for the fork

### ISSUE THREAD

**Issue by LemonBreezes** [armindarvish/consult-gh#101] opened 2024-01-06 12:45 UTC
Forking a GitHub repo with `consult-gh-repo-fork` does not add a remote for the new fork to the current Git repository.

**Comment by armindarvish** [comment] 2024-01-07 00:22
@LemonBreezes I am not sure I'm following this. can you please elaborate on what is your work flow and expected behavior?

Are you running `consult-gh-repo-fork` from inside a local git repo (cloned repo) and expect it to modify the remote? This is not what `gh` does by default and does not make a lot of sense to me to first clone a repo and then fork it. If anything I expect the opposite, first fork and then clone the forked repo. Either way you have to use the post-clone or post-fork hooks. You can check #39 for more info on that.

If there is something else you are trying to do, please describe the work-flow in details.

**Comment by LemonBreezes** [comment] 2024-01-07 00:38
> @LemonBreezes I am not sure I'm following this. can you please elaborate on what is your work flow and expected behavior?
> 
> Are you running `consult-gh-repo-fork` from inside a local git repo (cloned repo) and expect it to modify the remote? This is not what `gh` does by default and does not make a lot of sense to me to first clone a repo and then fork it. If anything I expect the opposite, first fork and then clone the forked repo. Either way you have to use the post-clone or post-fork hooks. You can check #39 for more info on that.
> 
> If there is something else you are trying to do, please describe the work-flow in details.

Yes. I mean that if you fork the current repo with `gh repo fork`, the CLI offers you the option of adding the new remote to your Git repository. I would like to be offered that option if I am forking the repository I am currently working in. 

Some time ago we worked on a feature where we can fork the current repository by using `M-n` to look in the future minibuffer history. This is a follow-up to that because if I do fork the current repository, it's often because I want to create a PR so I want to add the fork to my remotes.

**Comment by armindarvish** [comment] 2024-02-06 11:27
@LemonBreezes Sorry for the delayed follow up. 

This is a special case and one that can potentially cause unintended consequence. I am not willing to support this in general, but you can easily achieve this by defining some new functions (see example below).

Let me explain the potential problems first). In the CLI tool, when you use `gh repo fork`, by default it tries to fork the repo in the current directory and errors if you are not in a git repo. Therefore, there is a one to one relationship between forking and current directory, unless you pass other command line arguments. In consult-gh, the default is the opposite. The assumption is that you are not in a git repo directory (because you may be launching this from scratch buffer) and therefore you can fork any repos from any directory! For this reason, I am hesitant to mess up with remotes because let's say I am in a buffer visiting file A in repo A and I decide to launch consult-gh to look for repo B and decide to fork repo B. In this case, I do not want consult-gh to add any remotes to the current repo (i.e. repo A).

If you often fork current repo, then I suggest you simply define your own function based on `consult-gh-repo-fork`. Here is a very crude implementation as a starting point:

```elisp
(defun consult-gh-fork-current-repo (&optional name remote remote-name)
  "Forks the repo in the current directory as NAME.
if REMOTE is non-nil adds a remote to the current repo, otherwise queries the user
if both REMOT and REMOTE-NAME are non-nil, REMOTE-NAME is used as the name of the remote"
  (interactive)
  (if (consult-gh--get-repo-from-directory)
      (let* ((name (or name (read-string "name for forked repo: " (car (last (split-string (consult-gh--get-repo-from-directory) "\/"))))))
             (forkrepo (concat (consult-gh--get-current-username) "/" name))
             (remote (or remote (yes-or-no-p "add a remote? ")))
             (remote-name (or (and remote remote-name)
                              (and remote (read-string "name of remote? " "origin"))
                              (and remote "origin"))))
        ;; (print (format "name is %s, forkrepo is %s, remote is %s, remote-name is %s" name forkrepo remote remote-name))
        (consult-gh--command-to-string "repo" "fork" (if remote "--remote") (if (and remote-name (not (equal remote-name "origin"))) "--remote-name" "") (if  (and remote-name (not (equal remote-name "origin"))) remote-name ""))
        (message (format "current repo was forked to %s" (propertize forkrepo 'face 'font-lock-warning-face)))
        (run-hook-with-args 'consult-gh-repo-post-fork-hook forkrepo)
        (let ((inhibit-message t))
          forkrepo)
        )
    (consult-gh-repo-fork)))
``` 

Note that in the above function, there is a fall back to `consul-gh-repo-fork`in case there is not a git repo in the current directory.

**Comment by armindarvish** [comment] 2024-02-09 15:20
I am closing this now

**Closed by armindarvish** 2024-02-09 15:20 UTC

**Comment by LemonBreezes** [comment] 2024-02-09 15:45
> I am closing this now

Maybe this can be a customization option or a separate fork command.
